//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Team5Project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer_Vehicle_Booking1
    {
        public int Booking_id { get; set; }
        public string Vehicle_id { get; set; }
        public string Branch_Location { get; set; }
        public string Status { get; set; }
        public string Customer_id { get; set; }
    
        public virtual Customer_Profile Customer_Profile { get; set; }
        public virtual Vehicle_details Vehicle_details { get; set; }
    }
}
