//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Team5Project.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class Team5ProjectEntities8 : DbContext
    {
        public Team5ProjectEntities8()
            : base("name=Team5ProjectEntities8")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Branch_Admin> Branch_Admin { get; set; }
        public virtual DbSet<Customer_Profile> Customer_Profile { get; set; }
        public virtual DbSet<Customer_Vehicle_Booking1> Customer_Vehicle_Booking1 { get; set; }
        public virtual DbSet<User_Registration> User_Registration { get; set; }
        public virtual DbSet<Vehicle_Availability> Vehicle_Availability { get; set; }
        public virtual DbSet<Vehicle_details> Vehicle_details { get; set; }
        public virtual DbSet<VehicleSearch> VehicleSearches { get; set; }
        public virtual DbSet<Branch_Vehicle_Request> Branch_Vehicle_Request { get; set; }
    
        public virtual int Vehicle_Search(string sql)
        {
            var sqlParameter = sql != null ?
                new ObjectParameter("sql", sql) :
                new ObjectParameter("sql", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Vehicle_Search", sqlParameter);
        }
    
        public virtual ObjectResult<VehicleSearch> Fn_VehicleSearch(string sql)
        {
            var sqlParameter = sql != null ?
                new ObjectParameter("sql", sql) :
                new ObjectParameter("sql", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<VehicleSearch>("Fn_VehicleSearch", sqlParameter);
        }
    
        public virtual ObjectResult<VehicleSearch> Fn_VehicleSearch(string sql, MergeOption mergeOption)
        {
            var sqlParameter = sql != null ?
                new ObjectParameter("sql", sql) :
                new ObjectParameter("sql", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<VehicleSearch>("Fn_VehicleSearch", mergeOption, sqlParameter);
        }
    }
}
