//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Team5Project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vehicle_details
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Vehicle_details()
        {
            this.Customer_Vehicle_Booking1 = new HashSet<Customer_Vehicle_Booking1>();
            this.Vehicle_Availability = new HashSet<Vehicle_Availability>();
            this.Branch_Vehicle_Request = new HashSet<Branch_Vehicle_Request>();
        }
    
        public string Manufactures_name { get; set; }
        public string Vehicle_Code { get; set; }
        public Nullable<int> Ex_ShowRoom_Price { get; set; }
        public string Color { get; set; }
        public Nullable<int> No_of_Vehicles_Available { get; set; }
        public Nullable<int> Seating_Capacity { get; set; }
        public Nullable<System.DateTime> Stocks_Lasts_Still { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Customer_Vehicle_Booking1> Customer_Vehicle_Booking1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Vehicle_Availability> Vehicle_Availability { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Branch_Vehicle_Request> Branch_Vehicle_Request { get; set; }
    }
}
