//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Team5Project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VehicleSearch
    {
        public string Manufactures_name { get; set; }
        public string Vehicle_Code { get; set; }
        public string Branch_Location { get; set; }
        public Nullable<int> PriceRange { get; set; }
        public string Color { get; set; }
        public Nullable<int> Seating_Capacity { get; set; }
    }
}
